inventory/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'inventory'
urlpatterns =   [
    path('relief_inventory/', views.IndexView.as_view(), name='index'),
    path('received_packages/', views.ReceivedPackagesView.as_view(), name='received_packages'),
    path('received_packages/<int:reliefpackage_id>/', views.PackageItemsView.as_view(), name='package_items'),
    path('received_packages/<int:pk>/reception_verification/', views.ReceptionUpdateView.as_view(), name='reception'),
]

operations/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'operations'
urlpatterns =   [
    path('distribution_tracker/', views.IndexView.as_view(), name='index'),  
    path('<int:barangay_id>/barangay_households/', views.BarangayHouseholdsView.as_view(), name='barangay_households'),   
]

tulongtanggapagad/urls.py
from django.contrib import admin
from django.urls import path, include
from managementsystem import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managementsystem.urls')), # redirects to log in page
    path('households/', include('households.urls')),
    path('operations/', include('operations.urls')),
    path('inventory/', include('inventory.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/models.py
from django.db import models

# Create your models here.

operations/views.py
from django.views import generic
from django.urls import reverse
from managementsystem.models import *
from managementsystem.forms import *
from django.views.generic.edit import CreateView

class IndexView(generic.ListView): # loads up distribution tracker page
    template_name = 'operations/index.html'
    model = Barangay

class BarangayHouseholdsView(generic.ListView): # displays list of households per barangay in the list
    template_name = 'operations/barangay_households.html'
    model = Household

    def get_queryset(self): # captures the id/variable passed on to the url
        barangay = Barangay.objects.get(id = self.kwargs['barangay_id'])
        return Household.objects.filter(barangay = barangay)

operations/templates/operations/accomplishment_report.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Budget Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="640" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">

    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1" align="center">ACCOMPLISHMENT REPORT OF DISTRIBUTION OF RELIEF PACKS TO</h1>
                                <h1 class="display-1" align="center">BARANGAY CONSTITUENTS</h1>
                                <hr>
                                <h2>I. INTRODUCTION</h2>
                                <p>{{ report.introduction }}</p>
                                <h2>II. OBJECTIVES</h2>
                                <ul>
                                    {% for objective in objectives %}
                                        <li>{{ objective.objective }}</li>
                                    {% endfor %}
                                </ul>
                                <br>
                                <h2>III. HIGHLIGHTS AND ACCOMPLISHMENTS</h2>
                                <ul>
                                    {% for highlight in highlights %}
                                        <li>{{ highlight.highlight }}</li>
                                    {% endfor %}
                                </ul>
                                <br>
                                <hr>
                                <p align="right">Date Submitted:</p>
                                <p align="right">{{ report.report_date }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>    

</table>
</body>
</html>

operations/templates/operations/barangay_households.html
{% extends 'managementsystem/layout.html' %}

{% block content %}


<div class="card">
    <div class="card-header">
        <h2>Distribution Tracker</h2>
    </div>

    <div class="card-body">
        <h3 class="card-title">Households in Barangay</h3>
        <br></br>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">House No.</th>
              <th scope="col">Household Head</th>
              <th scope="col">Reception Status</th>
              <th scope="col">Reception Proof</th>
            </tr>
          </thead>
          <tbody>
            {% for household in household_list %}
              <tr>
                <td><h6>{{household}}</h6></td>
                <td><h6>{{household.household_head}}</h6></td>
                {% ifequal household.has_received_assistance True %}
                  <td>Recieved</td>
                {% else %}
                  <td> Not Recieved</td>
                {% endifequal %}
                <td><h6>{{MEDIA_URL}}{{household.reception_proof}}</h6></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>

    

{% endblock content %}

operations/templates/operations/budget_request.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Budget Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="640" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">

    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1" align="center">Relief Budget Request Form</h1>
                                {% comment %} <p class="lead" align="left">Requested by: </p> {% endcomment %}
                                <p>Requested by: {{ budgetrequest.requestor }}</p>
                                <p>Email: {{ budgetrequest.email }}</p>
                                <p>Date Requested: {{ budgetrequest.date_requested }}</p><br>
                                <p>The budget that you were offered based on a 
                                    standard cost of attendance (COA). Please review your COA before 
                                    submitting your request
                                    for a budget to determine if costs have already been included. 
                                </p>
    
                                <p>Request Period: <b>{{budgetrequest.request_period_start }}</b> to <b>{{ budgetrequest.request_period_end}}</b></p>
                                <hr>
                                    <div class="table-responsive">
                                        <table class="table table-striped table-sm">
                                          <thead>
                                            <tr>
                                              <th scope="col"><p>Budget Category</p>
                                                <p>(Complete items for which you are requesting an increase)</p>
                                              </th>
                                              <th scope="col">
                                                <p>Cost</p>
                                                <p>(Indicate the amount per month)</p>                                  
                                              </th>
                                              <th scope="col">
                                                Documentation Required
                                              </th>
                                            </tr>
                                          </thead>
                                          <tbody>
                                            {% for info in infos %}
                                              <tr>
                                                <td align="center">{{ info.budget_category }}</td>
                                                <td align="center">{{ info.cost }}</td>
                                                <td align="center">{{ info.required_documentation }}</td>
                                              </tr>
                                            {% endfor %}
                                          </tbody>
                                        </table>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>    

</table>
</body>
</html>

operations/templates/operations/index.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

<div class="card">
    <div class="card-header">
      Operations
    </div>
    <div class="card-body">
      <h3 class="card-title">Distribution Tracker</h3>
      <p class="card-text">Distribution status per barangay</p>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Barangay</th>
              <th scope="col">Households</th>
              <th scope="col">Received Assistance</th>
              <th scope="col">Completion</th>
            </tr>
          </thead>
          <tbody>
            {% for barangay in barangay_list %}
              <tr>
                <td><h6><a href="{% url 'operations:barangay_households' barangay.id %}">{{barangay}}</a></h6></td>
                <td>{{barangay.number_of_households}}</td>
                <td>{{barangay.number_of_received_assistance}}</td>
                <td>{{barangay.completion_status}}%</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div>
    <br></br>
    
{% endblock content %}

operations/templates/operations/monitoring_report.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Budget Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="640" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">

    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1" align="center">MONITORING REPORT</h1>
                                <hr>
                                <div class="table-responsive">
                                    <table class="table table-striped table-sm">
                                      <thead>
                                        <tr>
                                          <th scope="col">Municipality</th>
                                          <th scope="col">Households Affected</th>
                                          <th scope="col">Persons Affected</th>
                                          <th scope="col">Households Served</th>
                                          <th scope="col">Persons Served</th>
                                          <th scope="col">Relief Pack Quantity</th>
                                          <th scope="col">Cost Spent</th>
                                          <th scope="col">Remarks</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                          <tr>
                                            <td align="center">{{ report.municipality }}</td>
                                            <td align="center">{{ report.household_affected }}</td>
                                            <td align="center">{{ report.persons_affected }}</td>
                                            <td align="center">{{ report.household_served }}</td>
                                            <td align="center">{{ report.persons_served }}</td>
                                            <td align="center">{{ report.relief_pack_quantity }}</td>
                                            <td align="center">{{ report.cost_spent }}</td>
                                            <td align="center">{{ report.remarks }}</td>
                                          </tr>
                                      </tbody>
                                    </table>
                                </div>
                                <br>
                                <hr>
                                <p align="right">Date Submitted:</p>
                                <p align="right">{{ report.pub_date }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>    

</table>
</body>
</html>

operations/templates/operations/supply_request.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Supply Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="640" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">

    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1" align="center">Relief Supply Request Form</h1>
                                <h2 class="display-2" align="center">(Inventory)</h2>
                                <p>Organization: {{ supplyrequest.organization }}</p>
                                <p>Date Form Completed: {{ supplyrequest.date_form_completed }}</p>
                                <p>Date Needed By: {{ supplyrequest.date_needed_by }}</p>
                                <p>Contact Person: {{ supplyrequest.contact_person }}  Contact Number: {{ supplyrequest.contact_number }}</p><br>
                                <hr>
                                <div class="table-responsive">
                                        <table class="table table-striped table-sm">
                                          <thead>
                                            <tr>
                                              <th scope="col">Item Name</th>
                                              <th scope="col">Item Description</th>
                                              <th scope="col">Item Category</th>
                                              <th scope="col">Quantity</th>
                                              <th scope="col">Cost/Price</th>
                                              <th scope="col">Sub Total</th>
                                            </tr>
                                          </thead>
                                          <tbody>
                                            {% for info in infos %}
                                              <tr>
                                                <td align="center">{{ info.item_name }}</td>
                                                <td align="center">{{ info.item_description }}</td>
                                                <td align="center">{{ info.item_category }}</td>
                                                <td align="center">{{ info.quantity }}</td>
                                                <td align="center">{{ info.cost }}</td>
                                                <td align="center">{{ info.sub_total }}</td>
                                              </tr>
                                            {% endfor %}
                                          </tbody>
                                        </table>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>    

</table>
</body>
</html>

operations/templates/operations/tracking_report.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Budget Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0;">
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="640" style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;">

    <div id="layoutError">
        <div id="layoutError_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-6">
                            <div class="text-center mt-4">
                                <h1 class="display-1" align="center">TRACKING REPORT</h1>
                                <hr>
                                <div class="table-responsive">
                                    <table class="table table-striped table-sm">
                                      <thead>
                                        <tr>
                                          <th scope="col">Barangay</th>
                                          <th scope="col">Registered Households</th>
                                          <th scope="col">Received Assistance</th>
                                          <th scope="col">Completion Rate</th>
                                          <th scope="col">Remarks</th>
                                        </tr>
                                      </thead>
                                      <tbody>
                                          <tr>
                                            <td align="center">{{ report.barangay }}</td>
                                            <td align="center">{{ report.registered_households }}</td>
                                            <td align="center">{{ report.received_assistance }}</td>
                                            <td align="center">{{ report.completion_rate|stringformat:".2f" }}%</td>
                                            <td align="center">{{ report.remarks }}</td>
                                          </tr>
                                      </tbody>
                                    </table>
                                </div>
                                <br>
                                <hr>
                                <p align="right">Date Submitted:</p>
                                <p align="right">{{ report.pub_date }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>    

</table>
</body>
</html>