households/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'households'
urlpatterns =   [
    path('household_list/', views.IndexView.as_view(), name='index'),
    path('SMS/', views.SMSCreateView.as_view(), name='SMS'),
    path('registration/', views.RegistrationMenuView.as_view(), name='registration_menu'),
    path('import/', views.importFile, name='import_file'),
    path('registration/register/', views.RegistrationCreateView.as_view(), name='register'),
    path('registration/<int:pk>/update/', views.HouseholdUpdateView.as_view(), name='update'),
    path('household_list/<int:pk>/delete/', views.HouseholdDeleteView.as_view(), name='delete'),
    path('household_list/<int:pk>/reception_verification/', views.ReceptionUpdateView.as_view(), name='reception'),
]

inventory/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'inventory'
urlpatterns =   [
    path('relief_inventory/', views.IndexView.as_view(), name='index'),
    path('received_packages/', views.ReceivedPackagesView.as_view(), name='received_packages'),
    path('received_packages/<int:reliefpackage_id>/', views.PackageItemsView.as_view(), name='package_items'),
    path('received_packages/<int:pk>/reception_verification/', views.ReceptionUpdateView.as_view(), name='reception'),
]

tulongtanggapagad/urls.py
from django.contrib import admin
from django.urls import path, include
from managementsystem import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managementsystem.urls')), # redirects to log in page
    path('households/', include('households.urls')),
    path('operations/', include('operations.urls')),
    path('inventory/', include('inventory.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

households/models.py
from django.db import models

# Create your models here.

households/forms.py
from multiprocessing.sharedctypes import Value
from extra_views import ModelFormSetView
from managementsystem.models import Household, Member
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from django.forms import ModelForm, modelformset_factory

MemberFormSet = modelformset_factory(
    Member, fields=('firstname',
              'middlename',
              'lastname',
              'occupation',
              'gender',
              'birthday',), extra=1
)

class MemberForm(ModelForm):
    class Meta:
      model = Member
      fields = ['firstname',
              'middlename',
              'lastname',
              'occupation',
              'gender',
              'birthday',]

households/views.py
from ast import Try
from datetime import datetime
from logging import exception
from django.http import request, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from households.forms import *
from managementsystem.models import *
from managementsystem.forms import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.conf import settings  
from twilio.rest import Client
from django.contrib import messages
from django.shortcuts import redirect
from django.forms import *
import openpyxl
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory
from extra_views.generic import GenericInlineFormSetView

class IndexView(generic.ListView):         
    template_name = 'households/index.html'
    model = Household

class RegistrationMenuView(generic.ListView):
    template_name = 'households/registration_menu.html'
    model = Household
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super(RegistrationMenuView, self).get_context_data(**kwargs)
        context['new_households'] = Household.objects.all().order_by('-id')[:20]
        return context

class SMSCreateView(CreateView):
    template_name = 'households/sms.html'
    model = SMSMessage
    fields = ['message_title', 'message_content']
    
    def get_success_url(self):

        # test code. however unable to proceed testing with PH number due to trial account limitations.
        message_to_broadcast = ("message")
        client = Client("AC9d1a45e08480c7a61e5851636f7235c2", "4f121bbb233d0f88bdba37066efbe06b")

        client.messages.create(to="+639760125144", from_="+17407614481", body=message_to_broadcast) 

        return reverse('households:SMS')

    def get_context_data(self, **kwargs): #displaying messages
        # Call the base implementation first to get a context
        context = super(SMSCreateView, self).get_context_data(**kwargs)
        context['messages'] = SMSMessage.objects.all()
        return context

class ReceptionUpdateView(UpdateView):
    model = Household
    fields = ['reception_proof', 'has_received_assistance']
    template_name = 'households/reception.html'
    
    def get_success_url(self):
        message_to_broadcast = ("Relief package received! Date: " + str(datetime.today))
        client = Client("AC9d1a45e08480c7a61e5851636f7235c2", "4f121bbb233d0f88bdba37066efbe06b")
        client.messages.create(to="+639760125144", from_="+17407614481", body=message_to_broadcast) 

        return reverse('households:index')

class MembersInline(InlineFormSetFactory):
    model = Member
    extra = 0
    
    fields = ['firstname',
              'middlename',
              'lastname',
              'occupation',
              'gender',
              'birthday',]

    # configures inline fk model in the form
    factory_kwargs = {'extra': 1, 'max_num': 5,
                        'can_order': False, 'can_delete': True,}
                        
class RegistrationCreateView(CreateWithInlinesView):
    template_name = 'households/registration.html'
    model = Household
    inlines = [MembersInline]
    fields = ['house_number', 
              'street',
              'subdivision',
              'zone',
              'barangay',
              'household_head_firstname',
              'household_head_middlename',
              'household_head_lastname',
              'monthly_income',
              'contact_number',]
              
    def get_success_url(self):
        return reverse('households:registration_menu')

class HouseholdUpdateView(UpdateWithInlinesView):
    template_name = 'households/update_household.html'
    model = Household
    inlines = [MembersInline]
    fields = ['house_number', 
              'street',
              'subdivision',
              'zone',
              'barangay',
              'household_head_firstname',
              'household_head_middlename',
              'household_head_lastname',
              'monthly_income',
              'contact_number',]
              
    def get_success_url(self):
        return reverse('households:registration_menu')


class HouseholdDeleteView(DeleteView):
    template_name = 'households/delete_household.html'
    model = Household
              
    def get_success_url(self):
        return reverse('households:registration_menu')

def importFile(request):
    if "GET" == request.method:
        return reverse('households:registration_menu')
    elif request.method == "POST":
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size

        wb = openpyxl.load_workbook(excel_file)

        # getting a particular sheet by name out of many sheets
        worksheet = wb.active
        print(worksheet)

        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row

        i = 0
        for row in worksheet.iter_rows():
            row_data = list()
    
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)
            if i > 0:
                Household.objects.update_or_create(
                    house_number = row_data[0],
                    street = row_data[1],
                    subdivision = row_data[2],
                    zone = row_data[3],
                    barangay = row_data[4],
                    city = row_data[5],
                    province = row_data[6],
                    household_head_firstname = row_data[7],
                    household_head_middlename = row_data[8],
                    household_head_lastname = row_data[9],
                    monthly_income = row_data[10],
                    contact_number = row_data[11],
                    number_of_household_members = row_data[12],
                )
            i += 1		
        return HttpResponseRedirect(reverse("households:registration_menu"))

households/templates/households/delete_household.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

<div class="card">
    <div class="card-header">
      Households
    </div>
    <div class="card-body">
      <h2 class="card-title">Registered Households</h2>
      <hr>
      <div class="card-body" align="center">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to remove {{object.household_head_lastname}} household from the system? </p>
            {{ form.as_p }}
            <input class="btn btn-danger" type="submit" value="Remove">
        </form>
      </div>
    </div>
  </div>
    <br></br>

{% endblock content %}

households/templates/households/index.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Households
    </div>
    <div class="card-body">
      <h2 class="card-title">Registered Households</h2>
      <p class="card-text">View Households list and confirm relief reception</p>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">House No.</th>
              <th scope="col">Household Head</th>
              <th scope="col">Address</th>
              <th scope="col">Monthly Income</th>
              <th scope="col">Number of Members</th>
              <th scope="col">Reception Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for household in household_list %}
              <tr>
                <td>{{household}}</td>
                <td>{{household.household_head}}</td>
                <td>{{household.address}}</td>
                <td>{{household.monthly_income}}</td>
                <td>{{household.number_of_members}}</td>
                {% if household.has_received_assistance == True %}
                  <td>Recieved</td>
                  <td><button class="btn btn-secondary" disabled>Relief Assistance Received</button></td>
                {% else%}
                  <td> Not Recieved</td>
                  <td><a class="btn btn-primary" href="{% url 'households:reception' household.id %}">Verify Reception</button></td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}

households/templates/households/reception.html
{% extends 'managementsystem/layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<div class="card">
    <div class="card-header">
      Households
    </div>
    <div class="card-body">
      <h2 class="card-title">Registered Households</h2>
      <p class="card-text">View Households list and confirm relief reception</p>
      <div class="card-body" align="center">
        <form method="post">{% csrf_token %}
            <div class="fieldWrapper">
              {% bootstrap_field form.reception_proof %}
            </div>
            <div class="fieldWrapper">
              <p>Check to confirm if household {% bootstrap_field form.has_received_assistance show_lable=True%}</p>
            </div>
            <input class="btn btn-primary" type="submit" value="Update">
        </form>
      </div>
    </div>
  </div>
    <br></br>

{% endblock content %}

households/templates/households/registration.html
{% extends 'managementsystem/layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Registration
    </div>
    <div class="card-body">
      <h2 class="card-title">Household registration</h2>
      <p class="card-text">Register new households</p>
      <hr>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="container">
          <div class="row">
            <div class="col-md"> {% comment %} hh add col {% endcomment %}
              {% comment %} household address info {% endcomment %}
              <div class="card">
                <div class="card-header">
                  Household Address Information
                </div>
                <div class="card-body">
                  <div class="fieldWrapper">
                    {% bootstrap_field form.house_number%}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.street %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.subdivision %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.zone %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.barangay %}
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md"> {% comment %} hh info col {% endcomment %}
              {% comment %} household head info {% endcomment %}
              <div class="card">
                <div class="card-header">
                  Household Head Information
                </div>
                <div class="card-body">
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_firstname %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_middlename %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_lastname %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.monthly_income %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.contact_number %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <hr> 
        <h4>Members:</h4>
        <br>
        {% for formset in inlines  %}
            <div class="container">
              <div class="row">
                <div class="col-md">
                  <div class="card">
                    <div class="card-header">
                      Household Member Information
                    </div>
                    <div class="card-body">
                      {% bootstrap_formset formset %}
                      <hr>
                      {% buttons submit='Add another member' formset.form.extra|add:'1' %}{% endbuttons %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
        {% endfor %}

          <input type="submit" value="Save" class="btn btn-primary">
      </form>
    </div>
  </div>
    <br></br>
      
{% endblock %}

households/templates/households/registration_menu.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Registration
    </div>
    <div class="card-body">
      <h2 class="card-title">Household registration</h2>
      <p class="card-text">Register households</p>
      
      <div class="d-grid gap-3">
        <a type="button" class="btn btn-primary btn-block" href="{% url 'households:register'%}">Register Household</a>
        
        <br>
        <div>
          <hr>
          <h4>Import from file (.xslx):</h4>

          <form action="{% url "households:import_file" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
            {% csrf_token %}
            <div class="form-group">
                <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
                <div class="col-md-8">
                    <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
                </div>                    
            </div>
            <div class="form-group">
              <br>                    
                <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                     <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
                </div> 
            </div>
          </form>
        </div>
        <hr>
      <p class="card-text">Households registered/imported:</p>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">House No.</th>
                  <th scope="col">Household Head</th>
                  <th scope="col">Address</th>
                  <th scope="col">Monthly Income</th>
                  <th scope="col">Number of Members</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              {% for new_household in new_households %}
                <tr>
                  <td>{{new_household.house_number}}</td>
                  <td><h6><a href="{% url 'households:update' new_household.id %}">{{new_household.household_head}}</a></h6></td>
                  <td>{{new_household.address}}</td>
                  <td>{{new_household.monthly_income}}</td>
                  <td>{{new_household.number_of_members}}</td>
                  <td><a href="{% url 'households:delete' new_household.id %}" class="btn btn-danger">Remove</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}

households/templates/households/sms.html
{% extends 'managementsystem/layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

<!-- message input card -->
<div class="card">
  <div class="card-header">
    SMS Update
  </div>
  <div class="card-body">
    <h3 class="card-title">Distribution Operation SMS Update</h3>
    <p class="card-text">Update households regarding the distribution thru SMS below :</p>

        <!-- SMS form -->
        <form method="post">
        {% csrf_token %}
        
        {% bootstrap_form form %}
        
          <input type="submit" value="Send" class="btn btn-primary">
        </form>
        
  </div>
</div>

<!-- message records logs card -->
<div class="card">
    <div class="card-body">
        <h4 class="card-title">SMS Message Logs</h4>

        <!-- logs grid -->

        <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Message</th>
              <th scope="col">Date Sent</th>
            </tr>
          </thead>
          <tbody>
          {% for message in messages %}
            <tr>
                <td>{{message.message_title}}</td>
                <td>{{message.message_content}}</td>
                <td>{{message.date_sent}}</td>
              </tr>
          {% endfor %}
              
          </tbody>
        </table>
      </div>


    </div>
</div>



{% endblock content %}

households/templates/households/update_household.html
{% extends 'managementsystem/layout.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Households
    </div>
    <div class="card-body">
      <h2 class="card-title">Update household Information</h2>
      <hr>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="container">
          <div class="row">
            <div class="col-md"> {% comment %} hh add col {% endcomment %}
              {% comment %} household address info {% endcomment %}
              <div class="card">
                <div class="card-header">
                  Household Address Information
                </div>
                <div class="card-body">
                  <div class="fieldWrapper">
                    {% bootstrap_field form.house_number%}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.street %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.subdivision %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.zone %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.barangay %}
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md"> {% comment %} hh info col {% endcomment %}
              {% comment %} household head info {% endcomment %}
              <div class="card">
                <div class="card-header">
                  Household Head Information
                </div>
                <div class="card-body">
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_firstname %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_middlename %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.household_head_lastname %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.monthly_income %}
                  </div>
                  <div class="fieldWrapper">
                    {% bootstrap_field form.contact_number %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <hr> 
        <h4>Members:</h4>
            <br>
            {% for formset in inlines  %}
            <div class="container">
              <div class="row">
                <div class="col-md">
                  <div class="card">
                    <div class="card-header">
                      Household Member Information
                    </div>
                    <div class="card-body">
                      {% bootstrap_formset formset %}
                      <hr>
                      {% buttons submit='Add another member' formset.form.extra|add:'1' %}{% endbuttons %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
        {% endfor %}
        
          <input type="submit" value="Update" class="btn btn-primary">
      </form>
    </div>
  </div>
    <br></br>
      
{% endblock %}