inventory/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'inventory'
urlpatterns =   [
    path('relief_inventory/', views.IndexView.as_view(), name='index'),
    path('received_packages/', views.ReceivedPackagesView.as_view(), name='received_packages'),
    path('received_packages/<int:reliefpackage_id>/', views.PackageItemsView.as_view(), name='package_items'),
    path('received_packages/<int:pk>/reception_verification/', views.ReceptionUpdateView.as_view(), name='reception'),
]

tulongtanggapagad/urls.py
from django.contrib import admin
from django.urls import path, include
from managementsystem import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managementsystem.urls')), # redirects to log in page
    path('households/', include('households.urls')),
    path('operations/', include('operations.urls')),
    path('inventory/', include('inventory.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models

# Create your models here.

inventory/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from managementsystem.models import *
from managementsystem.forms import *
from django.views.generic.edit import CreateView, UpdateView

# Create your views here.

class IndexView(generic.ListView):         
    template_name = 'inventory/index.html'
    model = Item

class ReceivedPackagesView(generic.ListView):         
    template_name = 'inventory/received_packages.html'
    model = ReliefPackage

class PackageItemsView(generic.ListView):         
    template_name = 'inventory/received_package_items.html'
    model = ReliefPackage
    
    def get_queryset(self):
        return ReliefPackage.objects.filter(id = self.kwargs['reliefpackage_id'])

class ReceptionUpdateView(UpdateView):
    model = ReliefPackage
    fields = ['reception_status']
    template_name = 'inventory/reception.html'

    def get_success_url(self):
        return reverse('inventory:received_packages')

inventory/templates/inventory/index.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Inventory
    </div>
    <div class="card-body">
      <h2 class="card-title">Relief Stock Inventory</h2>
      <p class="card-text">List of relief goods in stock</p>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Item Name</th>
              <th scope="col">Number of Stocks</th>
              <th scope="col">Is Donated</th>
              <th scope="col">Fund Source</th>
            </tr>
          </thead>
          <tbody>
            {% for item in item_list %}
              <tr>
                <td>{{item}}</td>
                <td>{{item.get_number_of_stocks}}</td>
                <td>{{item.is_donated}}</td>
                <td>{{item.fund_source}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table> 
      </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}

inventory/templates/inventory/received_package_items.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Inventory
    </div>
    <div class="card-body">
      <h2 class="card-title">Received Relief Packages</h2>
      <p class="card-text">List of items included in the relief package</p>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Items</th>
            </tr>
          </thead>
          <tbody>
            {% for reliefpackage in reliefpackage_list %}
              {% for items in reliefpackage.relief_items.all %}
                <tr>
                  <td>{{items}}</td>
              </tr>
              {% endfor %}
            {% endfor %}
          </tbody>
        </table> 
      </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}

inventory/templates/inventory/received_packages.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Inventory
    </div>
    <div class="card-body">
      <h2 class="card-title">Received Relief Packages</h2>
      <p class="card-text">List of received approved relief packages</p>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Date Received</th>
              <th scope="col">Date of Approval</th>
              <th scope="col">Approval Instruction</th>
              <th scope="col">Reception</th>
            </tr>
          </thead>
          <tbody>
            {% for reliefpackage in reliefpackage_list %}
              {% if reliefpackage.status == "APPROVED" %}
                <tr>
                  <td><h6><a href="{% url 'inventory:package_items' reliefpackage.id %}">{{reliefpackage.name}}</a></h6></td>
                  <td>{{reliefpackage.date_received}}</td>
                  <td>{{reliefpackage.date_of_approval}}</td>
                  <td>{{reliefpackage.approval_instruction|safe}}</td>
                  
                  {% if reliefpackage.reception_status == False %}
                    <td><a class="btn btn-primary" href="{% url 'inventory:reception' reliefpackage.id %}">Confirm Reception</button></td>
                  {% else %}
                    <td><a class="btn btn-secondary" disabled>Received</button></td>
                  {% endif %}
                </tr>
              {% elif reliefpackage.status == "approved" %}
                <tr>
                  <td><h6><a href="{% url 'inventory:package_items' reliefpackage.id %}">{{reliefpackage.name}}</a></h6></td>
                  <td>{{reliefpackage.date_received}}</td>
                  <td>{{reliefpackage.date_of_approval}}</td>
                  <td>{{reliefpackage.approval_instruction|safe}}</td>
                  
                  {% if reliefpackage.reception_status == False %}
                    <td><a class="btn btn-primary" href="{% url 'inventory:reception' reliefpackage.id %}">Confirm Reception</button></td>
                  {% else %}
                    <td><a class="btn btn-secondary" disabled>Received</button></td>
                  {% endif %}
                </tr>
              {% endif %}
            {% endfor %}
          </tbody>
        </table> 
      </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}

inventory/templates/inventory/reception.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

  <div class="card">
    <div class="card-header">
      Inventory
    </div>
    <div class="card-body">
      <h2 class="card-title">Received Relief Packages</h2>
      <p class="card-text">List of received approved relief packages</p>
      <div class="card-body" align="center">
        <form method="post">{% csrf_token %}
          <h2>Confirm relief package reception?</h2>
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Confirm">
        </form>
      </div>
    </div>
  </div>
    <br></br>
      
{% endblock %}