inventory/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'inventory'
urlpatterns =   [
    path('relief_inventory/', views.IndexView.as_view(), name='index'),
    path('received_packages/', views.ReceivedPackagesView.as_view(), name='received_packages'),
    path('received_packages/<int:reliefpackage_id>/', views.PackageItemsView.as_view(), name='package_items'),
    path('received_packages/<int:pk>/reception_verification/', views.ReceptionUpdateView.as_view(), name='reception'),
]

managementsystem/urls.py
from django.urls import path

from . import views #from *this* directory import views.py

app_name = 'managementsystem'
urlpatterns =   [
    path('', views.login_request, name='index'),     # routes to login page
    path('main/', views.mainpage, name='main'),
    path('updates/', views.UpdatesView.as_view(), name='updates'),
    path('main/unauthorized/', views.unauthorized_access, name='unauthorized'),
    path('admin/', views.admin, name='admin'),
]

tulongtanggapagad/urls.py
from django.contrib import admin
from django.urls import path, include
from managementsystem import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('managementsystem.urls')), # redirects to log in page
    path('households/', include('households.urls')),
    path('operations/', include('operations.urls')),
    path('inventory/', include('inventory.urls')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managementsystem/models.py
from email.policy import default
from turtle import update
from django.db import models 
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.db.models import Count, Sum
from datetime import date, datetime
from django.core.files.storage import FileSystemStorage
from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth.models import User
from django.forms import FloatField
from pytz import timezone
from django.core.mail import send_mail, EmailMessage
from django.utils.safestring import mark_safe
from phonenumber_field.modelfields import PhoneNumberField
from django.template.loader import get_template
from django.template import Context

eligibility_storage = FileSystemStorage(location='/media/photos/eligibility_proof')
reception_storage = FileSystemStorage(location='/media/photos/reception_proof')

class Barangay(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, choices=settings.BARANGAYS_LIST)
    municipality = models.CharField(max_length=256, default='Pili')

    def number_of_households(self):
        households = Household.objects.filter(barangay = self)
        return households.count()
    
    def number_of_received_assistance(self):
        households = Household.objects.filter(barangay = self, has_received_assistance = True)
        return households.count()
    
    def completion_status(self):
        household = self.number_of_households()
        assisted = self.number_of_received_assistance()
        try:
            completion_status = assisted / household * 100
        except ZeroDivisionError:
            completion_status = 0.0

        return completion_status

    def __str__(self):
        return self.name

# Household < Family < Resident
class Household(models.Model):
    house_number = models.IntegerField(default=0)
    street = models.CharField(max_length=50, default='')
    subdivision = models.CharField(max_length=50, default='N/A', null=True)
    zone = models.IntegerField(default=0)
    barangay = models.CharField(max_length=50, choices=settings.BARANGAYS_LIST,null=True)
    city = models.CharField(max_length=50, default='Pili')
    province = models.CharField(max_length=50, default='Camarines Sur')

    household_head_firstname = models.CharField(max_length=50, default='')
    household_head_middlename = models.CharField(max_length=50, default='')
    household_head_lastname = models.CharField(max_length=50, default='')

    monthly_income = models.FloatField(default=0.00)
    contact_number = PhoneNumberField()

    number_of_household_members = models.IntegerField(default=1, null=True)

    reception_proof = models.ImageField(upload_to='reception_proof',  blank=True, null=True)

    has_received_assistance = models.BooleanField(default=False)

    def __str__(self):
        return str(self.house_number)
    
    def address(self):
        return self.street + ', ' + self.subdivision + ', Zone ' + str(self.zone) + ', ' + str(self.barangay) + ', ' + str(self.city) + ', ' + str(self.province)
    
    def household_head(self):
        return self.household_head_lastname + ', ' + self.household_head_firstname + ' ' + self.household_head_middlename[0].upper()

    def number_of_members(self):
        member = Member.objects.filter(household_group = self)
        if member.count() > 0:
            return member.count()
        elif member.count() == 0:
            return self.number_of_household_members

class Member(models.Model):
    household_group = models.ForeignKey(Household, on_delete=CASCADE, null=True)
    firstname = models.CharField(max_length=50, default='')
    middlename = models.CharField(max_length=50, default='')
    lastname = models.CharField(max_length=50, default='')
    occupation = models.CharField(max_length=50, default='')
    gender = models.CharField(max_length=15, choices=settings.GENDERS_LIST)
    birthday = models.DateField(default=date.today)

    def __str__(self):
        return self.firstname + ' ' + self.middlename[0].upper() + ' ' + self.lastname

class SMSMessage(models.Model):
    message_title = models.CharField(max_length=50, default='title')
    message_content = models.TextField(max_length=500, null=True)
    date_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.message_title

# Relief Goods < Items < Donors

class Item(models.Model):
    name = models.CharField(max_length=50)
    quantity = models.IntegerField(default=1)
    fund_source = models.CharField(max_length=50, choices=[('donated', 'donated'),
                                                            ('local funds', 'local funds'),
                                                            ('national funds', 'national funds'),
                                                            ('international funds', 'international funds')]) #dropdown
    date_restocked = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Inventory'

    def get_number_of_stocks(self):
        items = Item.objects.filter(name = self)
        return items.count()

STATUS_CHOICES = (
    ('pending','PENDING'),
    ('approved', 'APPROVED'),
)

class ReliefPackage(models.Model):
    name = models.CharField(max_length=25, default='relief package')
    date_received = models.DateTimeField(auto_now_add=True)
    destination = models.CharField(max_length=256,  choices=settings.BARANGAYS_LIST, null=False)       # might create address model
    is_donated = models.BooleanField(default=False)
    relief_items = models.ManyToManyField(Item, default='')
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='pending')
    date_of_approval = models.DateTimeField(null=True, blank=True)
    approval_instruction = RichTextField(null=True, blank=True)
    reception_status = models.BooleanField(default=False)
    
    def update (self, *args, **kwargs):
        self.date_of_approval = datetime.now
        super(ReliefPackage, self).update(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Donor(models.Model):
    relief_package = models.ForeignKey(ReliefPackage, unique=True, on_delete=CASCADE)
    firstname = models.CharField(max_length=50, default='')
    middlename = models.CharField(max_length=50, default='')
    lastname = models.CharField(max_length=50, default='')
    email = models.EmailField(max_length=254, null=True)
    contact_number = PhoneNumberField()

    def __str__(self):
        return self.firstname + ' ' + self.middlename[0].upper() + ' ' + self.lastname

class News(models.Model):
    title = models.CharField(max_length=50, default='')
    message = RichTextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'News'
    
    def __str__(self):
        return self.title

# Monitoring reports methods

def get_families_affected(municipality):
    families = Household.objects.filter(city = municipality)
    return families.count()

def get_persons_affected(municipality):
    families = Household.objects.filter(city = municipality)
    member_count = 0
    for persons in families:
        member_count += persons.number_of_members()

    return member_count
    
def get_families_served(municipality):
    families = Household.objects.filter(city = municipality).filter(has_received_assistance = True)
    return families.count()

def get_persons_served(municipality):
    families = Household.objects.filter(city = municipality).filter(has_received_assistance = True)
    member_count = 0
    for persons in families:
        member_count += persons.number_of_members()

    return member_count

# End Monitoring reports methods

class MonitoringReport(models.Model):
    municipality = models.CharField(max_length=50, default='Pili')
    household_affected = models.IntegerField(default=0)
    persons_affected = models.IntegerField(default=0)
    household_served = models.IntegerField(default=0)
    persons_served = models.IntegerField(default=0)
    remarks = models.CharField(max_length=50, null=True, default='')
    relief_pack_quantity = models.IntegerField(default=0)
    cost_spent = models.FloatField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Monitoring Reports (DSWD)' 
    
    def save(self, *args, **kwargs):
        self.household_affected = get_families_affected(self.municipality)
        self.persons_affected = get_persons_affected(self.municipality)
        self.household_served = get_families_served(self.municipality)
        self.persons_served = get_persons_served(self.municipality)
        self.relief_pack_quantity = ReliefPackage.objects.count()
        self.cost_spent = sum(Fund.objects.all().values_list('amount', flat=True))
        super(MonitoringReport, self).save(*args, **kwargs)
        
        template = get_template('D:/Capstone/web project/tulongtanggapagad/operations/templates/operations/monitoring_report.html')
        
        context = Context({'report': self}).flatten()
        content = template.render(context)

        mail = EmailMessage(
            'Monitoring Report ' + str(self.pub_date), 
            content, 
            settings.EMAIL_HOST_USER, 
            ['connivinggod7@gmail.com'],
            )
        mail.content_subtype = 'html'
        mail.send()

#Tracking reports methods

def get_number_of_registered_households(barangay):
        households = Household.objects.filter(barangay = barangay)
        return households.count()
    
def get_number_of_received_assistance(barangay):
    households = Household.objects.filter(barangay = barangay, has_received_assistance = True)
    return households.count()

def get_completion_status(barangay):

managementsystem/forms.py
from django import forms
from .models import *
 
 
# creating a form
class SMSMessageForm(forms.ModelForm):
    
    message_title = forms.CharField(max_length=50)
    message_content = forms.Textarea()

    # create meta class
    class Meta:
        # specify model to be used
        model = SMSMessage
 
        # specify fields to be used
        fields = [
            "message_title",
            "message_content",
        ]

managementsystem/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from .models import Household, News, RiskAssessment, RiskAssessmentInfo
from django.contrib.auth.models import User
from django import forms
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django.views import generic

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(data=request.POST)
		
		if form.is_valid():
			return redirect("managementsystem:main")
	else:
		form = AuthenticationForm()
	return render(request=request, template_name="managementsystem/login.html", context={"login_form":form})
    
def mainpage(request):
	pdra = RiskAssessment.objects.order_by('-assessment_date')[:1]
	assessmentinfo = RiskAssessmentInfo.objects.filter(assessment_form=pdra)
	context = {'riskassessment': pdra, 'riskassessmentinfo': assessmentinfo}
	return render(request, 'managementsystem/mainpage.html', context)

class UpdatesView(generic.ListView):
	template_name = 'managementsystem/updates_history.html'
	model = RiskAssessment
	paginate_by = 5

def unauthorized_access(request):
    return render(request, 'managementsystem/unauthorized.html')

def admin(request):
    return HttpResponseRedirect(reverse('admin:index'))

managementsystem/templates/managementsystem/login.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Login - TulongTanggapAgad</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'managementsystem/css/styles.css' %}" rel="stylesheet">
        
        <!-- Bootstrap core JS -->
        <script src="{% static 'managementsystem/js/scripts.js' %}" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><img src="{% static 'managementsystem/assets/img/mswd_logo.png' %}" width="90" height="90" style="vertical-align:middle;margin:0px 190px"></div>
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">TulongTanggapAgad</h3></div>
                                    <div class="card-body">
                                        <div class="container py-4">    
                                            <h2 align="center">Login</h2>
                                            <br>
                                            <form align="center" method="post">
                                                {% csrf_token %}
                                                {% bootstrap_form login_form%}
                                                    <input class="btn btn-primary" type="submit" value="Sign In" align="center">
                                            </form>
                                        </div>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutAuthentication_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; TulongTanggapAgad 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

managementsystem/templates/managementsystem/mainpage.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

<div class="card">
  <div class="card-header">
    Home
  </div>
  <div class="card-body">
    <h1 class="card-title">Welcome!</h1>
    {% for pdra in riskassessment %}
      <div class="card">
        <div class="card-header">
          Risk Assessment Evaluation (<i><b>{{pdra.assessment_date}}</b></i>):
        </div>
        <div class="card-body">
          <h4>Workplace Location:</h4>
          {{pdra.workplace_location}}
          <br></br>
          <h5>Assessment Conductor:</h5>
          {{pdra.assessment_conductor}}
          <br></br>
          <h5>Reviewed By:</h5>
          {{pdra.reviewed_by}}
          <br></br>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">Risk</th>
                  <th scope="col">Livelihood</th>
                  <th scope="col">Hazard Risk/Impact</th>
                  <th scope="col">Actions Required</th>
                  <th scope="col">Action Taker</th>
                  <th scope="col">Action Date</th>
                  <th scope="col">Response Strategy</th>
                  <th scope="col">Evaluation Results</th>
                </tr>
              </thead>
              <tbody>
                {% for info in riskassessmentinfo %}
                  <tr>
                    <td>{{ info.risk }}</td>
                    <td>{{ info.livelihood }}</td>
                    <td>{{ info.livelihood }}</td>
                    <td>{{ info.hazard_level }}</td>
                    <td>{{ info.action_taker }}</td>
                    <td>{{ info.action_date }}</td>
                    <td>{{ info.response_strategy }}</td>
                    <td>{{ info.evaluation_results }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>
      </div>
    {% endfor %}
    
  </div>
  <a class="btn btn-secondary" type="button" align="right" href="{% url 'managementsystem:updates' %}">view updates history</a>
</div>
  <br></br>

{% endblock %}

managementsystem/templates/managementsystem/unauthorized.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

 <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">Unauthorized</h1>
                                    <p class="lead">No Access</p>
                                    <p>Contact admin to access this feature.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>

{% endblock %}

managementsystem/templates/managementsystem/updates_history.html
{% extends 'managementsystem/layout.html' %}

{% block content %}

<div class="card">
  <div class="card-header">
    Home
  </div>
  <div class="card-body">
    <h2 class="card-title">Updates history</h2>
    <br>
    {% for pdra in riskassessment_list %}
      <div class="card">
        <div class="card-header">
          Risk Assessment Evaluation (<i><b>{{pdra.assessment_date}}</b></i>):
        </div>
        <div class="card-body">
          <h4>Workplace Location:</h4>
          {{pdra.workplace_location}}
          <br></br>
          <h5>Assessment Conductor:</h5>
          {{pdra.assessment_conductor}}
          <br></br>
          <h5>Reviewed By:</h5>
          {{pdra.reviewed_by}}
          <br></br>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
  <br></br>

{% endblock %}